//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrchardDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class JCMA_LOGTABLE
    {
        public decimal LOG_ID { get; set; }
        public string TABLE_LOCATION { get; set; }
        public string OLDVAL { get; set; }
        public string NEWVAL { get; set; }
    }
}
