//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrchardDB
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class JCMA_FIELDS
    {
        public JCMA_FIELDS()
        {
            this.JCMA_CHEMICALS = new ObservableCollection<JCMA_CHEMICALS>();
            this.JCMA_COORDINATES = new ObservableCollection<JCMA_COORDINATES>();
            this.JCMA_PICKS = new ObservableCollection<JCMA_PICKS>();
        }
    
        public decimal FIELD_ID { get; set; }
        public string FARM_NAME { get; set; }
        public string CROP { get; set; }
        public string VARIETY { get; set; }
    
        public virtual ObservableCollection<JCMA_CHEMICALS> JCMA_CHEMICALS { get; set; }
        public virtual ObservableCollection<JCMA_COORDINATES> JCMA_COORDINATES { get; set; }
        public virtual JCMA_FARM JCMA_FARM { get; set; }
        public virtual ObservableCollection<JCMA_PICKS> JCMA_PICKS { get; set; }
    }
}
