//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrchardDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class JCMA_EMPLOYEE
    {
        public JCMA_EMPLOYEE()
        {
            this.JCMA_PICKS = new ObservableListSource<JCMA_PICKS>();
        }
    
        public decimal EMP_ID { get; set; }
        public string NAME { get; set; }
        public string PHONE { get; set; }
        public string ADDRESS { get; set; }
        public string FARM_NAME { get; set; }
        public Nullable<System.DateTime> S_DATE { get; set; }
        public Nullable<System.DateTime> E_DATE { get; set; }
    
        public virtual JCMA_FARM JCMA_FARM { get; set; }
        public virtual ObservableListSource<JCMA_PICKS> JCMA_PICKS { get; set; }
    }
}
