//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrchardDB
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class JCMA_FARM
    {
        public JCMA_FARM()
        {
            this.JCMA_EMPLOYEE = new ObservableCollection<JCMA_EMPLOYEE>();
            this.JCMA_FIELDS = new ObservableCollection<JCMA_FIELDS>();
        }
    
        public string FARM_NAME { get; set; }
        public string LOCATION { get; set; }
        public string OWNER { get; set; }
    
        public virtual ObservableCollection<JCMA_EMPLOYEE> JCMA_EMPLOYEE { get; set; }
        public virtual ObservableCollection<JCMA_FIELDS> JCMA_FIELDS { get; set; }
    }
}
