//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrchardDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class JCMA_BIN
    {
        public JCMA_BIN()
        {
            this.JCMA_PICKS = new ObservableListSource<JCMA_PICKS>();
        }
    
        public decimal BIN_ID { get; set; }
        public System.DateTime D_DATE { get; set; }
        public Nullable<int> WEIGHT { get; set; }
        public string BIN_TYPE { get; set; }
        public Nullable<decimal> LATITUDE { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
        public Nullable<int> MAX_CAP { get; set; }
        public Nullable<System.DateTime> P_DATE { get; set; }
    
        public virtual ObservableListSource<JCMA_PICKS> JCMA_PICKS { get; set; }
    }
}
