//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrchardDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ODBEntities : DbContext
    {
        public ODBEntities()
            : base("name=ODBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<JCMA_BIN> JCMA_BIN { get; set; }
        public DbSet<JCMA_CHEMICALS> JCMA_CHEMICALS { get; set; }
        public DbSet<JCMA_COORDINATES> JCMA_COORDINATES { get; set; }
        public DbSet<JCMA_EMPLOYEE> JCMA_EMPLOYEE { get; set; }
        public DbSet<JCMA_FARM> JCMA_FARM { get; set; }
        public DbSet<JCMA_FIELDS> JCMA_FIELDS { get; set; }
        public DbSet<JCMA_PICKS> JCMA_PICKS { get; set; }
    }
}
