//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrchardDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ODBEntities : DbContext
    {
        public ODBEntities()
            : base("name=ODBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<JCMA_BIN> JCMA_BIN { get; set; }
        public DbSet<JCMA_CHEMICALS> JCMA_CHEMICALS { get; set; }
        public DbSet<JCMA_COORDINATES> JCMA_COORDINATES { get; set; }
        public DbSet<JCMA_EMPLOYEE> JCMA_EMPLOYEE { get; set; }
        public DbSet<JCMA_FARM> JCMA_FARM { get; set; }
        public DbSet<JCMA_FIELDS> JCMA_FIELDS { get; set; }
        public DbSet<JCMA_PICKS> JCMA_PICKS { get; set; }
        public DbSet<JCMA_LOGTABLE> JCMA_LOGTABLE { get; set; }
    
        public virtual int INSERT_FARM(string iNS_FARM_NAME, string iNS_LOCATION, string iNS_OWNER)
        {
            var iNS_FARM_NAMEParameter = iNS_FARM_NAME != null ?
                new ObjectParameter("INS_FARM_NAME", iNS_FARM_NAME) :
                new ObjectParameter("INS_FARM_NAME", typeof(string));
    
            var iNS_LOCATIONParameter = iNS_LOCATION != null ?
                new ObjectParameter("INS_LOCATION", iNS_LOCATION) :
                new ObjectParameter("INS_LOCATION", typeof(string));
    
            var iNS_OWNERParameter = iNS_OWNER != null ?
                new ObjectParameter("INS_OWNER", iNS_OWNER) :
                new ObjectParameter("INS_OWNER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_FARM", iNS_FARM_NAMEParameter, iNS_LOCATIONParameter, iNS_OWNERParameter);
        }
    }
}
